### ISSUE TITLE
Translate README in any language

### ISSUE THREAD

**Issue by isatrio** [isatrio/mycsscv#1]
Basically I just want this repo translated in many languages. So please any translation are welcome

**Comment by lucabezerra** [comment]
@isatrio 
Where should the translation live? Any specific folder/file?

**Comment by categulario** [comment]
maybe README_<language code>.md? for example README_es.md, README_fr.md?

**Comment by isatrio** [comment]
OMG just seeing thist? didn't notice if someone commented on this issue.

Like @categulario said, @lucabezerra . it will be README_es.md, README_fr.md. If you still want to translate, I appreciate. If no, it's ok.
